spring:
  application:
    name: backend-content

server:
  port: 9021

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
tx-lcn:
  client:
    manager-address: 192.168.121.130:8070